type Like {
  user: User
}

type Comment {
  user: User
  name: String!
  text: String!
  avatar: String
}

type Post {
  user: User!
  name: String!
  text: String!
  avatar: String
  likes: [Like!]!
  comments: [Comment!]!
}

input NewPostInput {
  text: String!
  name: String!
  avatar: String!
  likes: [Like!]!
  comments: [Comment!]!
}

input UpdatePostInput {
  text: String!
  name: String!
  avatar: String
  likes: [Like!]!
  comments: [Comment!]!
}

extend type Query {
  post: Post!
  posts: [Post!]!
}

extend type Mutation {
  newPost(input: NewPostInput!): Post!
  updatePost(input: UpdatePostInput!): Post!
  removePost(id: ID!): Post!
}
