type User {
  _id: ID!
  username: String!
  email: String!
  avatar: String!
}

input NewUserInput {
  username: String!
  email: String!
  avatar: String!
  password: String!
}

input CurrentUserInput {
  username: String!
  email: String!
  password: String!
}

input UpdateUserInput {
  username: String!
  email: String
}

type Query {
  me: User!
}

type Mutation {
  signup(input: NewUserInput!): User!
  signin(input: CurrentUserInput): User!
  updateMe(input: UpdateUserInput!): User!
}
